apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: git-helm-sops-1
  namespace: argocd-dev
  annotations:
    recipients.argocd-notifications.argoproj.io: "webhook:msteams"
    environment: dev
spec:
  project: default
  description: Use helm repo and version to deploy release
  source:
    repoURL: 'https://github.com/sandeep-sensyne/gitops-app.git'
    targetRevision: v1.0
    path: helmChart
    plugin:
      name: sopsNdu
      env:
      - name: NS_VALUES
        value: "dev-values.yaml"
      - name: SOPS_VALUES
        value: "dev-secret-sops-values.yaml"
      - name: RELEASE_NAME
        value: "app1"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    retry:
      limit: 3 
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
    automated:
      prune: true
      selfHeal: true
