apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-helm-1
  namespace: argocd
spec:
  project: default
  description: Use helm from git repo to deploy release
  source:
    repoURL: 'https://github.com/sandeep-sensyne/gitops-app.git'
    targetRevision: HEAD
    path: helmChart
    helm:
      valueFiles:
        - values.yaml
        - dev-secret.yaml
    chart: git-helm-app-1
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

