apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-app-1
  namespace: argocd
spec:
  project: default
  description: Use helm repo and version to deploy release
  source:
    repoURL: 'https://sandeep-sensyne.github.io/gitops-app/'
    targetRevision: 0.1.4
    plugin:
      name: sopsNdu
      env:
        - name: NS_VALUES
          value: "dev-values.yaml"
        - name: SOPS_VALUES
          value: "dev-secret-sops-values.yaml"
        - name: RELEASE_NAME
          value: "app2"
    chart: gitops-app
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

