apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-job-1
  namespace: argocd
  annotations:
    recipients.argocd-notifications.argoproj.io: "webhook:msteams"
    environment: dev
spec:
  project: default
  description: Use K8S job with git hub to deploy release
  source:
    repoURL: 'https://github.com/sandeep-sensyne/k8s-job.git'
    targetRevision: HEAD
    path: sampleJob
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
